// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AddressAutocompleteController from "./address_autocomplete_controller"
application.register("address-autocomplete", AddressAutocompleteController)

import DestinationController from "./destination_controller"
application.register("destination", DestinationController)

import MapController from "./map_controller"
application.register("map", MapController)

import SearchCountriesController from "./search_countries_controller"
application.register("search-countries", SearchCountriesController)
